baseURL = "https://ashuntu.github.io/desktop-eng-releases"
languageCode = "en-gb"
title = "Desktop Engineering Releases"

[params]
author = "Canonical Ltd."
description = "The latest releases from each team, and their statuses."

[markup.goldmark.renderer]
unsafe = true
